routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\FeatureController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\HeaderController;
use App\Http\Controllers\Admin\MediaController;
use App\Http\Controllers\Admin\MetaController;
use App\Http\Controllers\Admin\PriceController;
use App\Http\Controllers\Admin\PriceTextController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\SliderController;


use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', [HomeController::class, 'index']);

Route::get('lang/{lang}', [HomeController::class, 'switchLang'])->name('lang.switch');
Route::get('admin_lang/{lang}', [AuthController::class, 'switchLang'])->name('admin_lang.switch');
Route::get('/admin_login', [AuthController::class, 'loginView'])->name('admin_login');
Route::post('/login', [AuthController::class, 'login']);
Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {



    Route::group(['middleware' => 'auth'], function () {
//        Route::get('/', [AuthController::class, 'home']);
        Route::resource('settings', SettingController::class);
        Route::resource('metas', MetaController::class);
        Route::resource('sections', SectionController::class);
        Route::post('/update/{id}', [SettingController::class,'update']);
        Route::resource('headers', HeaderController::class);
        Route::get('/download_header', [HeaderController::class, 'download']);
        Route::resource('services', ServicesController::class);
        Route::get('/del_service/{id}', [ServicesController::class, 'destroy']);
        Route::resource('gallery', GalleryController::class);
        Route::get('/del_gallery/{id}', [GalleryController::class, 'destroy']);
        Route::resource('features', FeatureController::class);
        Route::get('/del_feature/{id}', [FeatureController::class, 'destroy']);
        Route::resource('sliders', SliderController::class);
        Route::get('/del_slider/{id}', [SliderController::class, 'destroy']);
        Route::get('/download_slider/{id}', [SliderController::class, 'download']);
        Route::resource('questions', QuestionController::class);
        Route::get('/del_question/{id}', [QuestionController::class, 'destroy']);
        Route::resource('media', MediaController::class);
        Route::resource('prices', PriceController::class);
        Route::get('/del_price/{id}', [PriceController::class, 'destroy']);
        Route::resource('price_text', PriceTextController::class);

        Route::post('/update_whatsapp', [MediaController::class, 'updateWhatsapp']);
        Route::get('/edit_whatsapp', [MediaController::class, 'editWhatsapp']);

        Route::post('/update_call', [MediaController::class, 'updateCall']);
        Route::get('/edit_call', [MediaController::class, 'editCall']);

        Route::post('/update_mail', [MediaController::class, 'updateMail']);
        Route::get('/edit_mail', [MediaController::class, 'editMail']);

        Route::post('/update_phone', [MediaController::class, 'updatePhone']);
        Route::get('/edit_phone', [MediaController::class, 'editPhone']);

        ## Admins Routes
        Route::resource('admins', AdminController::class);
        Route::get('/admin_del/{id}', [AdminController::class, 'destroy']);
        Route::get('/users', [AdminController::class, 'users']);

        Route::get('/logout', [AuthController::class, 'logout']);

    });
});
Route::get('/{lang}', [HomeController::class, 'index']);

app/Models/Slider.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Slider extends Model implements TranslatableContract
{
    use HasFactory, Translatable;

    protected $fillable = ['image','button_link','button_type'];

    public $translatedAttributes = ['title','description','button_name'];

}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Slider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Response;

class SliderController extends Controller
{
    public function index(){
        $sliders=Slider::orderBy('created_at','desc')->get();
        return view('admin.sliders.index',compact('sliders'));
    }
    public function show($id){
        $slider=Slider::find($id);
        return view('admin.sliders.item',compact('slider'));
    }
    public function create(){
        return view('admin.sliders.create');
    }
    public function store(Request $request){
        if($request->file != '' ){
            $request->validate([
                'file' => 'mimes:csv,txt,xlx,xls,pdf,docx,pptx'
            ]);


            $path = 'files/sliders/';

            $file = $request->file;
            $imageExtension = $file->getClientOriginalExtension();
            $filename = time() . '.' . $imageExtension;
            $filename = $path.$filename;
            $file->move($path, $filename);

            $button_link= $filename;
            $button_type= 1;

        }elseif ($request->link != '' ){
            $button_link= $request->link;
            $button_type= 2;
        }




        if($request->image != '' ){

            $path = 'images/sliders/';

            $image = $request->image;
            $imageExtension = $image->getClientOriginalExtension();
            $filename = time() . '.' . $imageExtension;
            $filename = $path.$filename;
            $image->move($path, $filename);

            $image=$filename;


        }
        $slider=Slider::create([
            'button_type'    =>$button_type,
            'button_link'    =>$button_link,
            'image'    =>$image,
            'ar'=>['title'    => $request->title_ar,
                'description' => $request->description_ar,
                'button_name' => $request->button_name_ar
            ],
            'en'=>['title'    => $request->title_en,
                'description' => $request->description_en,
                'button_name' => $request->button_name_en
            ]
        ]);

        return redirect(route('admin_panel.sliders.index'));
    }
    public function edit(Request $request,$id){
        $slider=Slider::find($id);
        return view('admin.sliders.edit',['slider'=>$slider]);
    }

    public function update(Request $request,$id){
        $slider=Slider::find($id);
        if($request->file != '' ){
            $request->validate([
                'file' => 'mimes:csv,txt,xlx,xls,pdf,docx,pptx'
            ]);

            if($slider->button_type=='1'){
                (File::exists($slider->button_link)) ? File::delete($slider->button_link) : Null;
            }

            $path = 'files/sliders/';

            $file = $request->file;
            $imageExtension = $file->getClientOriginalExtension();
            $filename = time() . '.' . $imageExtension;
            $filename = $path.$filename;
            $file->move($path, $filename);

            $slider->update([
                'button_link'      =>$filename,
                'button_type'      =>1
            ]);

        }elseif ($request->link != '' ){
            if($slider->button_type=='1'){
                (File::exists($slider->button_link)) ? File::delete($slider->button_link) : Null;
            }

            $slider->update([
                'button_link'      =>$request->link,
                'button_type'      =>2
            ]);
        }
        if($request->image != '' ){

            (File::exists($slider->image)) ? File::delete($slider->image) : Null;
            $path = 'images/sliders/';

            $image = $request->image;
            $imageExtension = $image->getClientOriginalExtension();
            $filename = time() . '.' . $imageExtension;
            $filename = $path.$filename;
            $image->move($path, $filename);

            $slider->update([
                'image'      =>$filename
            ]);

        }

        $slider->update([
            'ar'=>['title'    => $request->title_ar,
                'description' => $request->description_ar,
                'button_name' => $request->button_name_ar
            ],
            'en'=>['title'    => $request->title_en,
                'description' => $request->description_en,
                'button_name' => $request->button_name_en
            ]
        ]);

        return redirect(route('admin_panel.sliders.index'));
    }
    public function destroy($id){
        $slider=Slider::find($id);
        (File::exists($slider->image)) ? File::delete($slider->image) : Null;
        (File::exists($slider->button_link)) ? File::delete($slider->button_link) : Null;
        $slider->delete();
        return redirect()->back();
    }
    public function download($id)
    {
        $slider=Slider::find($id);
        $file_path = $slider->button_link;
        return Response::download($file_path);
    }
}

resources/views/admin/sliders/create.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item "> {{trans('sidebar.award')}} </li>
                                    <li class="breadcrumb-item active">{{trans('admin.add_award')}} </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">{{trans('admin.add_award')}} </h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.sliders.store')}}" enctype="multipart/form-data" >
                                    @method('POST')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="inputAddress" class="form-label">{{trans('admin.image')}} </label>
                                            <input type="file" class="form-control"  placeholder="1234 Main St" name="image" required>
                                            <p style="color: red"> {{trans('admin.image_size')}} 1080*1920</p>
                                        </div>

                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">{{trans('admin.title_ar')}} </label>
                                            <input type="text" class="form-control"  name="title_ar" required>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">{{trans('admin.des_ar')}}  </label>
                                            <textarea  class="form-control"  name="description_ar" required></textarea>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">{{trans('admin.title_en')}}  </label>
                                            <input type="text" class="form-control"  name="title_en" required>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">{{trans('admin.des_en')}} </label>
                                            <textarea  class="form-control"  name="description_en" required></textarea>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">{{trans('admin.button_ar')}} </label>
                                            <input type="text" class="form-control"  name="button_name_ar" required>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">{{trans('admin.button_en')}} </label>
                                            <input type="text" class="form-control"  name="button_name_en" required>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="inputAddress" class="form-label"> {{trans('admin.file')}}  </label>
                                            {{--                                        <img alt="avatar" src="/{{$headers->file}}"  width="200" height="200"/>--}}
                                            <br><br>
                                            <input type="file" class="form-control"  placeholder="1234 Main St" name="file" >
                                        </div>
                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">{{trans('admin.web')}} </label>
                                                <input type="url" class="form-control"  name="link" >
                                        </div>


                                        <div class="col-6">
                                            <div class="text-center">
                                                <button type="submit" class="btn btn-primary">{{trans('admin.add')}}  </button>
                                            </div>
                                        </div>

                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/sliders/index.blade.php
@extends('admin.dashboard')

@section('content')
    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active">{{trans('sidebar.award')}} </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->


            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                  <div class="table-responsive" id="t1">
                                    <a class="btn btn-primary mb-2 me-4" href="{{route('admin_panel.sliders.create')}}">{{trans('admin.add_award')}}  </a>
                                    <table id="myTable1" class="table table-striped table-bordered table-sm">
                                        <thead>
                                        <tr>
                                            <th class="text-center" scope="col"></th>
                                            <th scope="col">{{trans('admin.image')}}  </th>
                                            <th scope="col">{{trans('admin.title_ar')}}  </th>
                                            <th scope="col">{{trans('admin.title_en')}}  </th>
                                            <th class="text-center" scope="col"></th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        <?php $counter=1;?>
                                        @foreach($sliders as $slider)

                                            <tr>

                                                <td>
                                                    <p class="text-center">{{$counter}}</p>
                                                    <span class="text-success"></span>
                                                    <?php $counter++;?>
                                                </td>
                                                <td>
                                                    <div class="media">
                                                        <div class="avatar me-2">
                                                            <img alt="avatar" src="/{{$slider->image}}" class="rounded-circle" />
                                                        </div>

                                                    </div>
                                                </td>
                                                <td>
                                                    <p class="mb-0">{{$slider->translate('ar')->title}}</p>
                                                    <span class="text-success"></span>
                                                </td>
                                                <td>
                                                    <p class="mb-0">{{$slider->translate('en')->title}}</p>
                                                    <span class="text-success"></span>
                                                </td>

                                                <td class="text-center">
                                                    <div class="action-btns">
                                                        <a href="{{route('admin_panel.sliders.show',$slider->id)}}" class="action-btn btn-view bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="عرض">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
                                                        </a>
                                                        <a href="{{route('admin_panel.sliders.edit',$slider->id)}}" class="action-btn btn-edit bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="تعديل">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
                                                        </a>
                                                        <a href="/admin_panel/del_slider/{{$slider->id}}" class="action-btn btn-delete bs-tooltip" data-toggle="tooltip" data-placement="top" title="حذف">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                                        </a>

                                                    </div>
                                                </td>
                                            </tr>

                                        @endforeach

                                        </tbody>

                                    </table>



                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>

        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

@endsection

resources/views/admin/sliders/item.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item">{{trans('sidebar.award')}} </li>
                                    <li class="breadcrumb-item active"> {{trans('admin.show_award')}} </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->

        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class=""> {{trans('admin.show_award')}}</h3>
                          </div>
                        <div class="" style="padding: 2%; font-weight: bold;">
                            <div class="container">

                                <div class="col-md-6 ">
{{--                                    <label for="inputAddress" class="form-label "> الصورة الرئيسية </label><br>--}}
                                    <img alt="avatar" src="/{{$slider->image}}"  width="200" height="200"/>
                                    <br><br>
                                </div>
                                <div class="col-md-6">
                                    <label> {{trans('admin.title_ar')}}  : </label>
                                    @if($slider->translate('ar')->title)
                                        <span>{{$slider->translate('ar')->title}}</span>
                                    @else
                                        <span>لايوجد</span>
                                    @endif
                                </div>
                                <div class="col-md-6">
                                    <label>{{trans('admin.des_ar')}}  : </label>
                                    @if($slider->translate('ar')->description)
                                        <span>{{$slider->translate('ar')->description}}</span>
                                    @else
                                        <span>لايوجد</span>
                                    @endif
                                </div>
                                <div class="col-md-6">
                                    <label>{{trans('admin.title_en')}}  : </label>
                                    @if($slider->translate('en')->title)
                                        <span>{{$slider->translate('en')->title}}</span>
                                    @else
                                        <span>لايوجد</span>
                                    @endif
                                </div>
                                <div class="col-md-6">
                                    <label>{{trans('admin.des_en')}}  : </label>
                                    @if($slider->translate('en')->description)
                                        <span>{{$slider->translate('en')->description}}</span>
                                    @else
                                        <span>لايوجد</span>
                                    @endif
                                </div>
                                <div class="col-md-6">
                                    <label >{{trans('admin.button_ar')}} : </label>
                                    @if($slider->translate('ar')->button_name)
                                        <span>{{$slider->translate('ar')->button_name}}</span>
                                    @else
                                        <span>لايوجد</span>
                                    @endif
                                </div>
                                <div class="col-md-6">
                                    <label >{{trans('admin.button_en')}} : </label>
                                    @if($slider->translate('en')->button_name)
                                        <span>{{$slider->translate('en')->button_name}}</span>
                                    @else
                                        <span>لايوجد</span>
                                    @endif
                                </div>
                                <div class="col-md-6">
                                    @if($slider->button_type=='1')
                                    <label >{{trans('admin.file')}} : </label>

                                        <a href="/admin_panel/download_slider/{{$slider->id}}" class='btn btn-ghost-info'>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-inbox"><polyline points="22 12 16 12 14 15 10 15 8 12 2 12"></polyline><path d="M5.45 5.11L2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"></path></svg>
                                        </a>
                                    @else

                                        <label >{{trans('admin.web')}} : </label>

                                        <a href="{{$slider->button_link}}">{{$slider->button_link}}</a>
                                    @endif
                                </div>

                            </div>

                        </div>

                        </div>
                    </div>
                </div>
            </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->
    </div>



@endsection